### ISSUE TITLE
compat with python2

### ISSUE THREAD

**Issue by 0xae** [schollz/howmanypeoplearearound#2]
Soo, this runs on python2 or what ?

**Comment by arne-cl** [comment]
On my machine, it doesn't:

```
~ $ howmanypeoplearearound 
Specify WiFi adapter (use ifconfig to determine): wlp2s0
Traceback (most recent call last):
  File "/home/arne/anaconda2/bin/howmanypeoplearearound", line 11, in <module>
    sys.exit(main())
  File "/home/arne/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/arne/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/arne/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arne/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/arne/anaconda2/lib/python2.7/site-packages/howmanypeoplearearound/__main__.py", line 65, in main
    adapter = shlex.quote(adapter)
AttributeError: 'module' object has no attribute 'quote'
```

**Comment by schollz** [comment]
It looks like its just shlex that is a problem. I could easily remove that dependency as someone mentioned to me that its possible to do sanitization without it. 

@0xae would you rather use Python2 or should I just put a badge labeling this as a Python3.3+ project?

**Comment by 0xae** [comment]
Halo there @schollz 
I've tested and it works like a charm
thanks,
