### ISSUE TITLE
No Module Named _Curses - Linux

### ISSUE THREAD

**Issue by PythonicCoder101** [schollz/howmanypeoplearearound#40]
Hi I am running linux and the program called howmanypeoplearearound seems to respond with:

Traceback (most recent call last):
  File "/usr/local/bin/howmanypeoplearearound", line 11, in <module>
    load_entry_point('howmanypeoplearearound==0.4.0', 'console_scripts', 'howmanypeoplearearound')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/howmanypeoplearearound/__main__.py", line 17, in <module>
    from pick import pick
  File "/usr/local/lib/python3.6/site-packages/pick/__init__.py", line 3, in <module>
    import curses
  File "/usr/local/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

Can anyone help me with this issue as I have tried to work around it with the response to the older version but that does not work either....

**Comment by kres0345** [comment]
What version of python do you use, have you installed all the requirements
etc
?

lør. 5. maj 2018 9.44 PM skrev PythonicCoder101 <notifications@github.com>:

**Comment by PythonicCoder101** [comment]
Hello. I am using python 3 as shown in the output logs of file error location. And I have installed the program using the pip installation method, "pip install howmanypeoplearearound"

**Comment by kres0345** [comment]
Try typing pip -V

søn. 6. maj 2018 9.49 PM skrev PythonicCoder101 <notifications@github.com>:

**Comment by PythonicCoder101** [comment]
Hello again, 
I have ran the command and gotten the result, pip version 10.0.0.1 - python 3.6

**Comment by kres0345** [comment]
Ok, the last few commands I've sent simply were to confirm you had the
correct version of python and pip, since it were correct, can you then try
to reinstall it?

tir. 8. maj 2018 4.03 AM skrev PythonicCoder101 <notifications@github.com>:

**Comment by juergenhoetzel** [comment]
> File "/usr/local/lib/python3.6/curses/**init**.py", line 13, in 
> from _curses import *

looks like you installed a self-compiled version of python which doesn't have curses support.
Most likely `ncurses-devel` (Header files) is missing on your system.
